# Generated by Django 4.1.9 on 2023-06-01 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('class_name', models.TextField()),
                ('kwargs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelschema',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name'),
        ),
        migrations.AddField(
            model_name='fieldschema',
            name='model_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tables.modelschema'),
        ),
        migrations.AddConstraint(
            model_name='fieldschema',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('model_schema'), name='unique_name-model_schema'),
        ),
    ]
